name: Rancher PushProx CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

permissions:
  contents: read

jobs:
  build:
    name : Build, test  & validate
    runs-on : ubuntu-latest
    strategy:
      matrix:
          include:
            - platform: linux/amd64
            - platform: linux/arm64
    steps:
      - name : Checkout repository
        uses : actions/checkout@v4
      - name : Set up Go
        uses : actions/setup-go@v5
        with:
          go-version: 1.22
      - name : Debug - WIP
        run : echo "uname -m is $(uname -m)"
      - name : CI
        run : make ci
